module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,3.05,True,2022-09-12T07:00:14,,
cowidev.vax.batch.australia,7.7,True,2022-09-12T07:00:18,,
cowidev.vax.batch.austria,2.26,True,2022-09-12T07:00:13,,
cowidev.vax.batch.belgium,1.6,True,2022-09-12T07:00:12,,
cowidev.vax.batch.bolivia,1.87,True,2022-09-12T07:00:13,,
cowidev.vax.batch.canada,5.97,True,2022-09-12T07:00:18,,
cowidev.vax.batch.chile,0.85,True,2022-09-12T07:00:13,,
cowidev.vax.batch.czechia,5.4,True,2022-09-12T07:00:18,,
cowidev.vax.batch.denmark,1.93,True,2022-09-12T07:00:15,,
cowidev.vax.batch.ecdc,129.09,True,2022-09-12T07:02:23,,
cowidev.vax.batch.ecuador,2.68,True,2022-09-12T07:00:18,,
cowidev.vax.batch.estonia,0.79,True,2022-09-12T07:00:19,,
cowidev.vax.batch.france,0.52,True,2022-09-12T07:00:19,,
cowidev.vax.batch.germany,1.7,True,2022-09-12T07:00:20,,
cowidev.vax.batch.greece,2.5,True,2022-09-12T07:00:21,,
cowidev.vax.batch.hong_kong,6.25,True,2022-09-12T07:00:25,,
cowidev.vax.batch.indonesia,,,2022-09-12T07:00:19,,
cowidev.vax.batch.ireland,0.41,True,2022-09-12T07:00:19,,
cowidev.vax.batch.israel,4.89,True,2022-09-12T07:00:24,,
cowidev.vax.batch.italy,10.96,True,2022-09-12T07:00:31,,
cowidev.vax.batch.japan,59.4,False,2022-09-12T07:05:09,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 236, in main
    Japan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 220, in export
    df = self.read().pipe(self.pipeline_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 156, in read
    df_latest = self.read_latest().pipe(self.pipe_latest)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 88, in read_latest
    dfs.append(self._read_xlsx(self.source_url, self.sheets, self.metrics))
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 97, in _read_xlsx
    xlsx = pd.ExcelFile(url_proxy)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1191, in __init__
    ext = inspect_excel_format(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py"", line 1070, in inspect_excel_format
    with get_handle(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 609, in get_handle
    ioargs = _get_filepath_or_buffer(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/io/common.py"", line 317, in _get_filepath_or_buffer
    reader = BytesIO(req.read())
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/http/client.py"", line 472, in read
    s = self._safe_read(self.length)
  File ""/home/owid/.pyenv/versions/3.9.6/lib/python3.9/http/client.py"", line 615, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(337034 bytes read, 13328 more expected)
","IncompleteRead(337034 bytes read, 13328 more expected)"
cowidev.vax.batch.jersey,0.72,True,2022-09-12T07:00:25,,
cowidev.vax.batch.latvia,22.67,True,2022-09-12T07:00:47,,
cowidev.vax.batch.lithuania,2.29,True,2022-09-12T07:00:27,,
cowidev.vax.batch.luxembourg,4.52,True,2022-09-12T07:00:32,,
cowidev.vax.batch.malaysia,0.52,True,2022-09-12T07:00:32,,
cowidev.vax.batch.malta,0.7,True,2022-09-12T07:00:32,,
cowidev.vax.batch.netherlands,,,2022-09-12T07:00:32,,
cowidev.vax.batch.new_zealand,11.0,True,2022-09-12T07:00:43,,
cowidev.vax.batch.norway,0.35,True,2022-09-12T07:00:33,,
cowidev.vax.batch.peru,3.03,True,2022-09-12T07:00:36,,
cowidev.vax.batch.portugal,,,2022-09-12T07:00:36,,
cowidev.vax.batch.romania,14.09,True,2022-09-12T07:00:50,,
cowidev.vax.batch.saudi_arabia,3.51,True,2022-09-12T07:00:46,,
cowidev.vax.batch.singapore,1.56,True,2022-09-12T07:00:48,,
cowidev.vax.batch.slovakia,101.02,True,2022-09-12T07:02:29,,
cowidev.vax.batch.slovenia,0.74,True,2022-09-12T07:00:49,,
cowidev.vax.batch.south_korea,14.27,False,2022-09-12T07:05:23,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 186, in main
    SouthKorea().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 169, in export
    df_base = self.read().pipe(self.pipeline_base)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 90, in pipeline_base
    df.pipe(self.pipe_rename_columns_raw)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 47, in pipe_rename_columns_raw
    self._check_format_multicols(df, columns_lv)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 62, in _check_format_multicols
    raise ValueError(f""Unknown columns in level {lv}: {diff}"")
ValueError: Unknown columns in level 0: Index(['스카이코비원'], dtype='object')
","Unknown columns in level 0: Index(['스카이코비원'], dtype='object')"
cowidev.vax.batch.spc,22.02,True,2022-09-12T07:01:12,,
cowidev.vax.batch.sweden,17.09,True,2022-09-12T07:01:29,,
cowidev.vax.batch.switzerland,44.15,True,2022-09-12T07:02:13,,
cowidev.vax.batch.trinidad_and_tobago,1.85,True,2022-09-12T07:02:15,,
cowidev.vax.batch.ukraine,,,2022-09-12T07:02:15,,
cowidev.vax.batch.united_kingdom,8.94,True,2022-09-12T07:02:24,,
cowidev.vax.batch.united_states,53.82,True,2022-09-12T07:03:17,,
cowidev.vax.batch.uruguay,4.66,True,2022-09-12T07:02:28,,
cowidev.vax.batch.zimbabwe,0.34,True,2022-09-12T07:02:29,,
cowidev.vax.incremental.africacdc,,,2022-09-12T07:02:29,,
cowidev.vax.incremental.antigua_barbuda,3.71,True,2022-09-12T07:02:32,,
cowidev.vax.incremental.aruba,1.17,True,2022-09-12T07:02:30,,
cowidev.vax.incremental.azerbaijan,,,2022-09-12T07:02:29,,
cowidev.vax.incremental.bahrain,1.22,True,2022-09-12T07:02:30,,
cowidev.vax.incremental.bangladesh,19.01,True,2022-09-12T07:02:49,,
cowidev.vax.incremental.barbados,1.25,True,2022-09-12T07:02:31,,
cowidev.vax.incremental.brazil,0.19,True,2022-09-12T07:02:31,,
cowidev.vax.incremental.bulgaria,0.89,True,2022-09-12T07:02:32,,
cowidev.vax.incremental.china,40.14,True,2022-09-12T07:03:12,,
cowidev.vax.incremental.costa_rica,,,2022-09-12T07:02:32,,
cowidev.vax.incremental.croatia,0.18,True,2022-09-12T07:02:32,,
cowidev.vax.incremental.cuba,2.06,True,2022-09-12T07:02:35,,
cowidev.vax.incremental.curacao,0.36,True,2022-09-12T07:02:35,,
cowidev.vax.incremental.cyprus,1.99,True,2022-09-12T07:02:37,,
cowidev.vax.incremental.dominican_republic,6.08,True,2022-09-12T07:02:43,,
cowidev.vax.incremental.el_salvador,1.14,True,2022-09-12T07:02:44,,
cowidev.vax.incremental.faeroe_islands,0.41,True,2022-09-12T07:02:45,,
cowidev.vax.incremental.fiji,0.0,True,2022-09-12T07:02:45,,
cowidev.vax.incremental.finland,0.22,True,2022-09-12T07:02:45,,
cowidev.vax.incremental.gabon,,,2022-09-12T07:02:45,,
cowidev.vax.incremental.georgia,0.52,True,2022-09-12T07:02:45,,
cowidev.vax.incremental.greenland,0.36,True,2022-09-12T07:02:46,,
cowidev.vax.incremental.guatemala,,,2022-09-12T07:02:46,,
cowidev.vax.incremental.guernsey,0.15,True,2022-09-12T07:02:46,,
cowidev.vax.incremental.hungary,0.88,True,2022-09-12T07:02:47,,
cowidev.vax.incremental.iceland,0.23,True,2022-09-12T07:02:47,,
cowidev.vax.incremental.india,0.9,True,2022-09-12T07:02:48,,
cowidev.vax.incremental.iran,,,2022-09-12T07:02:48,,
cowidev.vax.incremental.isle_of_man,0.84,True,2022-09-12T07:02:49,,
cowidev.vax.incremental.jamaica,5.47,True,2022-09-12T07:02:54,,
cowidev.vax.incremental.kazakhstan,8.39,True,2022-09-12T07:02:57,,
cowidev.vax.incremental.kosovo,17.23,True,2022-09-12T07:03:11,,
cowidev.vax.incremental.kyrgyzstan,4.07,True,2022-09-12T07:03:01,,
cowidev.vax.incremental.laos,2.24,True,2022-09-12T07:03:04,,
cowidev.vax.incremental.macao,15.5,True,2022-09-12T07:03:19,,
cowidev.vax.incremental.moldova,40.07,False,2022-09-12T07:06:03,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f880a86a490>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f880a86a490>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 59, in main
    Moldova().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 54, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 17, in read
    soup = get_soup(self.source_url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f880a86a490>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f880a86a490>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))"
cowidev.vax.incremental.monaco,41.09,True,2022-09-12T07:03:53,,
cowidev.vax.incremental.mongolia,0.98,True,2022-09-12T07:03:18,,
cowidev.vax.incremental.montenegro,0.13,True,2022-09-12T07:03:18,,
cowidev.vax.incremental.morocco,,,2022-09-12T07:03:18,,
cowidev.vax.incremental.myanmar,,,2022-09-12T07:03:18,,
cowidev.vax.incremental.nepal,,,2022-09-12T07:03:18,,
cowidev.vax.incremental.north_macedonia,,,2022-09-12T07:03:18,,
cowidev.vax.incremental.northern_cyprus,0.88,True,2022-09-12T07:03:19,,
cowidev.vax.incremental.paho,50.47,True,2022-09-12T07:04:09,,
cowidev.vax.incremental.pakistan,1.45,True,2022-09-12T07:03:20,,
cowidev.vax.incremental.philippines,,,2022-09-12T07:03:20,,
cowidev.vax.incremental.poland,0.36,True,2022-09-12T07:03:21,,
cowidev.vax.incremental.qatar,,,2022-09-12T07:03:21,,
cowidev.vax.incremental.russia,0.58,False,2022-09-12T07:06:03,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 80, in main
    Russia().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 66, in export
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 11, in read
    soup = get_soup(source)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
",Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
cowidev.vax.incremental.saint_lucia,,,2022-09-12T07:03:22,,
cowidev.vax.incremental.serbia,9.64,True,2022-09-12T07:03:31,,
cowidev.vax.incremental.south_africa,5.89,True,2022-09-12T07:03:37,,
cowidev.vax.incremental.spain,3.46,True,2022-09-12T07:03:39,,
cowidev.vax.incremental.sri_lanka,,,2022-09-12T07:03:37,,
cowidev.vax.incremental.suriname,15.15,True,2022-09-12T07:03:52,,
cowidev.vax.incremental.taiwan,5.87,True,2022-09-12T07:03:45,,
cowidev.vax.incremental.thailand,3.94,True,2022-09-12T07:03:48,,
cowidev.vax.incremental.turkey,0.55,True,2022-09-12T07:03:49,,
cowidev.vax.incremental.united_arab_emirates,,,2022-09-12T07:03:49,,
cowidev.vax.incremental.vietnam,,,2022-09-12T07:03:49,,
cowidev.vax.incremental.who,4.59,True,2022-09-12T07:03:54,,
cowidev.vax.incremental.zambia,0.95,True,2022-09-12T07:03:53,,
