module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,3.36,True,2022-08-31T07:00:14,,
cowidev.vax.batch.australia,3.17,True,2022-08-31T07:00:14,,
cowidev.vax.batch.austria,3.03,True,2022-08-31T07:00:14,,
cowidev.vax.batch.belgium,1.62,True,2022-08-31T07:00:12,,
cowidev.vax.batch.bolivia,2.55,True,2022-08-31T07:00:13,,
cowidev.vax.batch.canada,5.05,True,2022-08-31T07:00:17,,
cowidev.vax.batch.chile,1.1,True,2022-08-31T07:00:14,,
cowidev.vax.batch.czechia,2.86,True,2022-08-31T07:00:17,,
cowidev.vax.batch.denmark,3.68,True,2022-08-31T07:00:18,,
cowidev.vax.batch.ecdc,144.01,True,2022-08-31T07:02:38,,
cowidev.vax.batch.ecuador,2.01,True,2022-08-31T07:00:16,,
cowidev.vax.batch.estonia,0.86,True,2022-08-31T07:00:17,,
cowidev.vax.batch.france,0.83,True,2022-08-31T07:00:17,,
cowidev.vax.batch.germany,2.03,True,2022-08-31T07:00:19,,
cowidev.vax.batch.greece,2.76,True,2022-08-31T07:00:20,,
cowidev.vax.batch.hong_kong,12.21,True,2022-08-31T07:00:30,,
cowidev.vax.batch.indonesia,,,2022-08-31T07:00:18,,
cowidev.vax.batch.ireland,0.39,True,2022-08-31T07:00:18,,
cowidev.vax.batch.israel,9.21,True,2022-08-31T07:00:27,,
cowidev.vax.batch.italy,10.47,True,2022-08-31T07:00:30,,
cowidev.vax.batch.japan,133.9,True,2022-08-31T07:02:34,,
cowidev.vax.batch.jersey,2.33,True,2022-08-31T07:00:29,,
cowidev.vax.batch.latvia,15.91,True,2022-08-31T07:00:45,,
cowidev.vax.batch.lithuania,1.54,True,2022-08-31T07:00:31,,
cowidev.vax.batch.luxembourg,1.66,True,2022-08-31T07:00:31,,
cowidev.vax.batch.malaysia,0.66,True,2022-08-31T07:00:32,,
cowidev.vax.batch.malta,0.68,True,2022-08-31T07:00:32,,
cowidev.vax.batch.netherlands,,,2022-08-31T07:00:32,,
cowidev.vax.batch.new_zealand,11.03,True,2022-08-31T07:00:43,,
cowidev.vax.batch.norway,0.3,True,2022-08-31T07:00:32,,
cowidev.vax.batch.peru,3.24,True,2022-08-31T07:00:36,,
cowidev.vax.batch.portugal,,,2022-08-31T07:00:36,,
cowidev.vax.batch.romania,12.4,True,2022-08-31T07:00:48,,
cowidev.vax.batch.saudi_arabia,2.75,True,2022-08-31T07:00:46,,
cowidev.vax.batch.singapore,1.64,True,2022-08-31T07:00:47,,
cowidev.vax.batch.slovakia,72.96,True,2022-08-31T07:01:59,,
cowidev.vax.batch.slovenia,0.51,True,2022-08-31T07:00:48,,
cowidev.vax.batch.south_korea,76.59,True,2022-08-31T07:02:04,,
cowidev.vax.batch.spc,5.41,True,2022-08-31T07:00:53,,
cowidev.vax.batch.sweden,15.53,True,2022-08-31T07:01:09,,
cowidev.vax.batch.switzerland,70.73,True,2022-08-31T07:02:20,,
cowidev.vax.batch.trinidad_and_tobago,1.67,True,2022-08-31T07:02:00,,
cowidev.vax.batch.ukraine,,,2022-08-31T07:02:00,,
cowidev.vax.batch.united_kingdom,16.52,False,2022-08-31T07:04:01,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/united_kingdom.py"", line 89, in main
    UnitedKingdom().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/united_kingdom.py"", line 82, in export
    df_base = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/united_kingdom.py"", line 16, in read
    self._read_metrics(""areaType=overview""),
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/batch/united_kingdom.py"", line 37, in _read_metrics
    df = api.get_dataframe()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/uk_covid19/api_interface.py"", line 581, in get_dataframe
    data = self.get_json()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/uk_covid19/api_interface.py"", line 367, in get_json
    for response in self._get(DataFormat.JSON):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/uk_covid19/api_interface.py"", line 308, in _get
    raise FailedRequestError(response=response, params=api_params)
uk_covid19.exceptions.FailedRequestError: 
Request failed .... 500 - Internal Server Error
Response .......... {""response"":""An internal error occurred whilst processing your request, please try again. If the problem persists, please report as an issue and include your request."",""status_code"":500,""status"":""Internal Server Error""}
URL ............... https://api.coronavirus.data.gov.uk/v1/data?filters=areaType%3Doverview&structure=%7B%22date%22%3A%22date%22%2C%22location%22%3A%22areaName%22%2C%22areaCode%22%3A%22areaCode%22%2C%22people_vaccinated%22%3A%22cumPeopleVaccinatedFirstDoseByPublishDate%22%2C%22people_fully_vaccinated%22%3A%22cumPeopleVaccinatedSecondDoseByPublishDate%22%2C%22total_vaccinations%22%3A%22cumVaccinesGivenByPublishDate%22%2C%22total_boosters%22%3A%22cumPeopleVaccinatedThirdInjectionByPublishDate%22%2C%22vaccinations_age%22%3A%22vaccinationsAgeDemographics%22%7D&format=json&page=1
Decoded URL ....... https://api.coronavirus.data.gov.uk/v1/data?filters=areaType=overview&structure={""date"":""date"",""location"":""areaName"",""areaCode"":""areaCode"",""people_vaccinated"":""cumPeopleVaccinatedFirstDoseByPublishDate"",""people_fully_vaccinated"":""cumPeopleVaccinatedSecondDoseByPublishDate"",""total_vaccinations"":""cumVaccinesGivenByPublishDate"",""total_boosters"":""cumPeopleVaccinatedThirdInjectionByPublishDate"",""vaccinations_age"":""vaccinationsAgeDemographics""}&format=json&page=1
Parameters:
{ 'filters': 'areaType=overview',
  'format': 'json',
  'page': 1,
  'structure': '{""date"":""date"",""location"":""areaName"",""areaCode"":""areaCode"",""people_vaccinated"":""cumPeopleVaccinatedFirstDoseByPublishDate"",""people_fully_vaccinated"":""cumPeopleVaccinatedSecondDoseByPublishDate"",""total_vaccinations"":""cumVaccinesGivenByPublishDate"",""total_boosters"":""cumPeopleVaccinatedThirdInjectionByPublishDate"",""vaccinations_age"":""vaccinationsAgeDemographics""}'}

","
Request failed .... 500 - Internal Server Error
Response .......... {""response"":""An internal error occurred whilst processing your request, please try again. If the problem persists, please report as an issue and include your request."",""status_code"":500,""status"":""Internal Server Error""}
URL ............... https://api.coronavirus.data.gov.uk/v1/data?filters=areaType%3Doverview&structure=%7B%22date%22%3A%22date%22%2C%22location%22%3A%22areaName%22%2C%22areaCode%22%3A%22areaCode%22%2C%22people_vaccinated%22%3A%22cumPeopleVaccinatedFirstDoseByPublishDate%22%2C%22people_fully_vaccinated%22%3A%22cumPeopleVaccinatedSecondDoseByPublishDate%22%2C%22total_vaccinations%22%3A%22cumVaccinesGivenByPublishDate%22%2C%22total_boosters%22%3A%22cumPeopleVaccinatedThirdInjectionByPublishDate%22%2C%22vaccinations_age%22%3A%22vaccinationsAgeDemographics%22%7D&format=json&page=1
Decoded URL ....... https://api.coronavirus.data.gov.uk/v1/data?filters=areaType=overview&structure={""date"":""date"",""location"":""areaName"",""areaCode"":""areaCode"",""people_vaccinated"":""cumPeopleVaccinatedFirstDoseByPublishDate"",""people_fully_vaccinated"":""cumPeopleVaccinatedSecondDoseByPublishDate"",""total_vaccinations"":""cumVaccinesGivenByPublishDate"",""total_boosters"":""cumPeopleVaccinatedThirdInjectionByPublishDate"",""vaccinations_age"":""vaccinationsAgeDemographics""}&format=json&page=1
Parameters:
{ 'filters': 'areaType=overview',
  'format': 'json',
  'page': 1,
  'structure': '{""date"":""date"",""location"":""areaName"",""areaCode"":""areaCode"",""people_vaccinated"":""cumPeopleVaccinatedFirstDoseByPublishDate"",""people_fully_vaccinated"":""cumPeopleVaccinatedSecondDoseByPublishDate"",""total_vaccinations"":""cumVaccinesGivenByPublishDate"",""total_boosters"":""cumPeopleVaccinatedThirdInjectionByPublishDate"",""vaccinations_age"":""vaccinationsAgeDemographics""}'}
"
cowidev.vax.batch.united_states,39.19,True,2022-08-31T07:02:43,,
cowidev.vax.batch.uruguay,1.95,True,2022-08-31T07:02:19,,
cowidev.vax.batch.zimbabwe,1.02,True,2022-08-31T07:02:20,,
cowidev.vax.incremental.africacdc,,,2022-08-31T07:02:20,,
cowidev.vax.incremental.antigua_barbuda,4.26,True,2022-08-31T07:02:24,,
cowidev.vax.incremental.aruba,1.23,True,2022-08-31T07:02:21,,
cowidev.vax.incremental.azerbaijan,2.67,False,2022-08-31T07:04:04,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py"", line 113, in main
    Azerbaijan().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py"", line 108, in export
    data = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py"", line 26, in read
    data = self._parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py"", line 37, in _parse_data
    text = self._parse_pdf_text(url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/azerbaijan.py"", line 69, in _parse_pdf_text
    text = extract_text(f)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pdfminer/high_level.py"", line 146, in extract_text
    for page in PDFPage.get_pages(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pdfminer/pdfpage.py"", line 147, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/pdfminer/pdfdocument.py"", line 726, in __init__
    raise PDFSyntaxError('No /Root object! - Is this really a PDF?')
pdfminer.pdfparser.PDFSyntaxError: No /Root object! - Is this really a PDF?
",No /Root object! - Is this really a PDF?
cowidev.vax.incremental.bahrain,4.9,True,2022-08-31T07:02:29,,
cowidev.vax.incremental.bangladesh,19.11,True,2022-08-31T07:02:48,,
cowidev.vax.incremental.barbados,3.17,True,2022-08-31T07:02:36,,
cowidev.vax.incremental.brazil,0.12,True,2022-08-31T07:02:34,,
cowidev.vax.incremental.bulgaria,1.29,True,2022-08-31T07:02:35,,
cowidev.vax.incremental.china,40.24,True,2022-08-31T07:03:16,,
cowidev.vax.incremental.costa_rica,,,2022-08-31T07:02:36,,
cowidev.vax.incremental.croatia,0.21,True,2022-08-31T07:02:36,,
cowidev.vax.incremental.cuba,2.53,True,2022-08-31T07:02:38,,
cowidev.vax.incremental.curacao,0.38,True,2022-08-31T07:02:38,,
cowidev.vax.incremental.cyprus,0.66,True,2022-08-31T07:02:39,,
cowidev.vax.incremental.dominican_republic,6.56,True,2022-08-31T07:02:45,,
cowidev.vax.incremental.el_salvador,0.71,True,2022-08-31T07:02:40,,
cowidev.vax.incremental.faeroe_islands,0.38,True,2022-08-31T07:02:40,,
cowidev.vax.incremental.fiji,0.0,True,2022-08-31T07:02:40,,
cowidev.vax.incremental.finland,0.22,True,2022-08-31T07:02:40,,
cowidev.vax.incremental.gabon,,,2022-08-31T07:02:40,,
cowidev.vax.incremental.georgia,0.59,True,2022-08-31T07:02:41,,
cowidev.vax.incremental.greenland,0.51,True,2022-08-31T07:02:41,,
cowidev.vax.incremental.guatemala,,,2022-08-31T07:02:41,,
cowidev.vax.incremental.guernsey,0.19,True,2022-08-31T07:02:42,,
cowidev.vax.incremental.hungary,1.25,True,2022-08-31T07:02:43,,
cowidev.vax.incremental.iceland,0.48,True,2022-08-31T07:02:43,,
cowidev.vax.incremental.india,0.84,True,2022-08-31T07:02:44,,
cowidev.vax.incremental.iran,2.54,True,2022-08-31T07:02:46,,
cowidev.vax.incremental.isle_of_man,0.96,True,2022-08-31T07:02:45,,
cowidev.vax.incremental.jamaica,2.51,True,2022-08-31T07:02:48,,
cowidev.vax.incremental.kazakhstan,7.82,True,2022-08-31T07:02:53,,
cowidev.vax.incremental.kosovo,4.62,False,2022-08-31T07:04:08,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 82, in main
    Kosovo().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 77, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 23, in read
    df = self._parse_data(soup)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 32, in _parse_data
    soup = get_soup(link, verify=False)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://msh.rks-gov.net/10.230.0.57+9000/coviddashboard.html not reached! Error code 404 Not Found
",Source https://msh.rks-gov.net/10.230.0.57+9000/coviddashboard.html not reached! Error code 404 Not Found
cowidev.vax.incremental.kyrgyzstan,1.03,True,2022-08-31T07:02:49,,
cowidev.vax.incremental.laos,2.36,True,2022-08-31T07:02:50,,
cowidev.vax.incremental.macao,20.02,True,2022-08-31T07:03:09,,
cowidev.vax.incremental.moldova,40.06,False,2022-08-31T07:04:48,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 174, in _new_conn
    conn = connection.create_connection(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 96, in create_connection
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/connection.py"", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 699, in urlopen
    httplib_response = self._make_request(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 382, in _make_request
    self._validate_conn(conn)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 1010, in _validate_conn
    conn.connect()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 358, in connect
    conn = self._new_conn()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connection.py"", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f0d74ffe190>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/connectionpool.py"", line 755, in urlopen
    retries = retries.increment(
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/urllib3/util/retry.py"", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0d74ffe190>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 59, in main
    Moldova().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 54, in export
    df = self.read().pipe(self.pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/moldova.py"", line 17, in read
    soup = get_soup(self.source_url)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/venv/lib/python3.9/site-packages/requests/adapters.py"", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0d74ffe190>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))
","HTTPSConnectionPool(host='vaccinare.gov.md', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0d74ffe190>, 'Connection to vaccinare.gov.md timed out. (connect timeout=20)'))"
cowidev.vax.incremental.monaco,28.05,True,2022-08-31T07:03:19,,
cowidev.vax.incremental.mongolia,1.0,True,2022-08-31T07:02:54,,
cowidev.vax.incremental.montenegro,0.11,True,2022-08-31T07:02:54,,
cowidev.vax.incremental.morocco,,,2022-08-31T07:02:54,,
cowidev.vax.incremental.myanmar,,,2022-08-31T07:02:54,,
cowidev.vax.incremental.nepal,,,2022-08-31T07:02:54,,
cowidev.vax.incremental.north_macedonia,,,2022-08-31T07:02:54,,
cowidev.vax.incremental.northern_cyprus,0.78,True,2022-08-31T07:02:55,,
cowidev.vax.incremental.paho,49.77,True,2022-08-31T07:03:45,,
cowidev.vax.incremental.pakistan,1.51,True,2022-08-31T07:03:10,,
cowidev.vax.incremental.philippines,,,2022-08-31T07:03:10,,
cowidev.vax.incremental.poland,0.11,True,2022-08-31T07:03:10,,
cowidev.vax.incremental.qatar,,,2022-08-31T07:03:10,,
cowidev.vax.incremental.russia,0.52,False,2022-08-31T07:04:49,"Traceback (most recent call last):
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 80, in main
    Russia().export()
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 66, in export
    data = read(source).pipe(pipeline)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/vax/incremental/russia.py"", line 11, in read
    soup = get_soup(source)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/mnt/owid_live_covid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
",Source https://gogov.ru/articles/covid-v-stats not reached! Error code 502 Bad Gateway
cowidev.vax.incremental.saint_lucia,,,2022-08-31T07:03:11,,
cowidev.vax.incremental.serbia,5.99,True,2022-08-31T07:03:17,,
cowidev.vax.incremental.south_africa,8.0,True,2022-08-31T07:03:24,,
cowidev.vax.incremental.spain,4.72,True,2022-08-31T07:03:22,,
cowidev.vax.incremental.sri_lanka,,,2022-08-31T07:03:19,,
cowidev.vax.incremental.suriname,14.61,True,2022-08-31T07:03:34,,
cowidev.vax.incremental.taiwan,5.2,True,2022-08-31T07:03:27,,
cowidev.vax.incremental.thailand,3.41,True,2022-08-31T07:03:27,,
cowidev.vax.incremental.turkey,0.66,True,2022-08-31T07:03:28,,
cowidev.vax.incremental.united_arab_emirates,,,2022-08-31T07:03:27,,
cowidev.vax.incremental.vietnam,,,2022-08-31T07:03:27,,
cowidev.vax.incremental.who,3.97,True,2022-08-31T07:03:31,,
cowidev.vax.incremental.zambia,0.67,True,2022-08-31T07:03:28,,
